version: '3.8'

services:
  # PostgreSQL database with pgvector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: citetube-postgres
    environment:
      POSTGRES_DB: citetube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d citetube"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # vLLM server
  vllm:
    build: .
    container_name: citetube-vllm
    environment:
      - CUDA_VISIBLE_DEVICES=0
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/root/.cache/huggingface
    command: >
      python start_vllm.py
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    restart: unless-stopped

  # CiteTube application
  app:
    build: .
    container_name: citetube-app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - VLLM_HOST=vllm
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      vllm:
        condition: service_healthy
    command: >
      sh -c "
        python -c 'from dotenv import load_dotenv; load_dotenv(); from src.citetube.core.db import init_db; init_db()' &&
        python -m src.citetube.ui.app
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  model_cache:
    driver: local

networks:
  default:
    name: citetube-network